Adicionado suporte parcial para o IFFAR
GeovaneSchmitz/SIGAA-node-interface pull request #12
Opened 2021-08-02 23:58 UTC by matheus-nicolay

### Adicionado suporte parcial para o IFFAR - funções de login, vínculos, notas e informações pessoais.

**Issues**: 

1. Função getEmails() retorna um array vazio
2. Verificação de vínculos atual não verifica os vínculos dos alunos do IFFAR

2021-08-06 21:47 UTC, GeovaneSchmitz requested changes
A solução está quase perfeita, só tem um probleminha, você modificou a class SigaaStudentBond de forma que se eu aplicar, não vai funcionar mais em outras instituições porque essa class é comum a todos os outro item estão perfeitos, eu vou fazer um commit com a separação da class Bond para que seja mais fácil aplicar essa modificação somente no IFFAR

2021-08-06 23:43 UTC, GeovaneSchmitz commented on src/account/sigaa-account-iffar.ts
> +        if (count == 2) {
Não entendi o count ser igual a dois

2021-08-09 23:27 UTC, matheus-nicolay commented on src/account/sigaa-account-iffar.ts
> +        if (count == 2) {
Na verdade foi apenas uma forma improvisada de pegar o vínculo ativo. O count é igual a dois, pois o vínculo ativo do aluno sempre fica na segunda linha da tabela, sendo os demais os vínculos inativos. Está lógica, obviamente, não funcionário caso o usuário tenha mais de um vínculo ativo. Estou tentando de momento resolver essa issue

2022-09-22 15:34 UTC, GeovaneSchmitz commented
Como não teve atualização vou fechar esse pull request.

2022-09-22 15:34 UTC, closed without merging